ongr_elasticsearch:
  analysis:
    tokenizer:
      pathTokenizer:
        type: path_hierarchy
    analyzer:
      pathAnalyzer:
        tokenizer: pathTokenizer
  managers:
    default:
      index:
        index_name: su_articles
        hosts:
          - elasticsearch
      mappings:
        - SuluArticleBundle
    live:
      index:
        index_name: su_articles_live
        hosts:
          - elasticsearch
      mappings:
        - SuluArticleBundle